import dotenv from "dotenv";

dotenv.config({
  path: process.env.ENVIRONMENTS_FILE_PATH
    ? process.env.ENVIRONMENTS_FILE_PATH
    : ".env",
});

const envs = {
  SERVER_ID: process.env.SERVER_ID!,

  TICKETS_DISCORD_TOKEN: process.env.TICKETS_DISCORD_TOKEN!,
  OPEN_SALES_CATEGORY_ID: process.env.OPEN_SALES_CATEGORY_ID!,
  SALES_REQUEST_CHANNEL_ID: process.env.SALES_REQUEST_CHANNEL_ID!,

  ONBOARDING_DISCORD_TOKEN: process.env.ONBOARDING_DISCORD_TOKEN!,
  ONBOARDING_CATEGORY_ID: process.env.ONBOARDING_CATEGORY_ID!,
  WELCOME_CHANNEL_ID: process.env.WELCOME_CHANNEL_ID!,

  BACKOFFICE_SALES_TICKETS_DISCORD_TOKEN:
    process.env.BACKOFFICE_SALES_TICKETS_DISCORD_TOKEN!,
  BACKOFFICE_SALES_TICKETS_MANAGEMENT_CHANNEL_ID:
    process.env.BACKOFFICE_SALES_TICKETS_MANAGEMENT_CHANNEL_ID!,

  GC_ACCOUNT_SERVICE: JSON.parse(process.env.GC_ACCOUNT_SERVICE || "{}"),
  GC_SHEET_SERVICE_ACCOUNT_EMAIL: process.env.GC_SHEET_SERVICE_ACCOUNT_EMAIL!,
  GC_SHEET_SERVICE_ACCOUNT_PRIVATE_KEY:
    process.env.GC_SHEET_SERVICE_ACCOUNT_PRIVATE_KEY!.replace(/\\n/g, "\n"),

  OWNER_ID: process.env.OWNER_ID!,

  REDIS_URL: process.env.REDIS_URL!,

  LOCAL_PROJECT_ID: process.env.LOCAL_PROJECT_ID!,

  AUTH_ENV: process.env.AUTH_ENV || "cloud",
  FIRESTORE_ENV: process.env.FIRESTORE_ENV || "cloud",

  REQUEST_TIMEOUT_MS: process.env.REQUEST_TIMEOUT_MS
    ? parseInt(process.env.REQUEST_TIMEOUT_MS)
    : 120000,
  POLLING_INTERVAL_MS: process.env.POLLING_INTERVAL_MS
    ? parseInt(process.env.POLLING_INTERVAL_MS)
    : 200,

  CATALOGUE_ID: process.env.CATALOGUE_ID!,

  CATALOGUE_SYNC_CRON_EXPRESSION: process.env.CATALOGUE_SYNC_CRON_EXPRESSION!,
};

export default envs;
